services:
    _defaults:
        autowire: true
        autoconfigure: true

    c975L\XliffBundle\Controller\:
        resource: '../../Controller/*'

    c975L\XliffBundle\Service\:
        resource: '../../Service/*'
