services:
    _defaults:
        autowire: true
        autoconfigure: true

    c975L\XliffBundle\Controller\:
        resource: '../src/Controller/*'

    c975L\XliffBundle\Service\:
        resource: '../src/Service/*'
